### ISSUE TITLE
kubernetes_deployment does not support namespace_selector for pod_anti_affinity

### ISSUE THREAD

**Issue by matpen** [hashicorp/terraform-provider-kubernetes#1826] opened 2022-09-04 12:17 UTC
### Description

It looks like neither `kubernetes_deployment` nor  `kubernetes_deployment_v1` support the [namespace_selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#namespace-selector) field for `pod_anti_affinity` (and possibly for `pod_affinity`). This is unfortunate, because it is the only way to specify a match in "all namespaces" (by passing an empty selector).

### Potential Terraform Configuration

```hcl
resource "kubernetes_deployment" "my_app" {
  ...
  spec {
    ...
    template {
      ...
      spec {
        ...
        affinity {
          pod_anti_affinity {
            required_during_scheduling_ignored_during_execution {
              label_selector {
                match_expressions {
                  key = "app"
                  operator = "In"
                  values = ["my-app"]
                }
              }
              namespace_selector = {} # TODO this does not work
              topology_key = "kubernetes.io/hostname"
            }
          }
        }
        ...
```

### References

n / a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by flynnhandley** [comment] 2022-09-22 08:39
@alexsomesan, I can see [other resources](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Fkubernetes+namespace_selector&sxsrf=ALiCzsY3GtLdwX8jZkoWnjkHCQ0PqTw6VQ%3A1663835842671&source=hp&ei=wh4sY5GyJsPh4-EPlsOO8Ag&iflsig=AJiK0e8AAAAAYyws0jYp2ahTOBYkTZmpno64AFcpD-Up&ved=0ahUKEwiRm_XC_6f6AhXD8DgGHZahA44Q4dUDCAk&uact=5&oq=site%3Ahttps%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Fkubernetes+namespace_selector&gs_lcp=Cgdnd3Mtd2l6EAM6BAgjECc6BQgAEJECOgoIABCxAxCDARBDOgQIABBDOgsIABCABBCxAxCDAToRCC4QgAQQsQMQgwEQxwEQ0QM6DgguEIAEELEDEMcBENEDOggIABCABBCxAzoLCC4QgAQQsQMQ1AI6CgguEMcBENEDEEM6CwguEIAEELEDEIMBOgcIABCxAxAKOgsILhCABBDHARCvAToFCAAQgARQAFiRMGCbMmgAcAB4AIABsAGIAbAbkgEEMC4yNZgBAKABAaABAg&sclient=gws-wiz) have support for `namespace_selector`, would you be open to a PR for this enhancement?

**Comment by AlbertoSpinella** [comment] 2023-09-23 10:30
I can confirm that also in `pod_affinity` the block `namespace_selector` isn't recognized.

**Comment by Nox-404** [comment] 2023-12-19 10:14
Hello, is there any plan to implement this ?

**Comment by Nox-404** [comment] 2023-12-19 10:22
just noticed this PR: https://github.com/hashicorp/terraform-provider-kubernetes/pull/2020

**Comment by BBBmau** [comment] 2024-01-03 19:14
@Nox-404 it seems like the author of #2020 is taking some time to respond. You are more than welcome to grab what they've worked on and make the requested changes to get this merged

**Comment by BBBmau** [comment] 2024-10-11 06:47
@aayushsss1 this is a good issue to pick up. involves adding a new field which is not blocked by a k8s version block. You're open to work on it since the previous PR was closed a few months back.

**Comment by aayushsss1** [comment] 2024-10-11 12:57
@BBBmau sure I'll take a look into this!

**Comment by aayushsss1** [comment] 2024-10-30 14:40
@BBBmau It looks like namespace_selector is already supported for pod affinity and pod anti-affinity. Could you please let me know what additional work is required on this? Thanks!

https://github.com/hashicorp/terraform-provider-kubernetes/blob/af55e47b5bf8762cb0f90f38b44397d57e55e853/kubernetes/schema_affinity_spec.go#L169-L176

**Closed** 2024-11-14 16:46 UTC
Labels: enhancement, theme/coverage
