### ISSUE TITLE
(aws eks get-token --cluster-name <NAME>) from  terraform-provider-kubernetes cdk works fine local machine but not working in container environment

### ISSUE THREAD

**Issue by Jahadul-Rakib** [hashicorp/terraform-provider-kubernetes#1633] opened 2022-03-10 04:45 UTC
```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.default.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.default.certificate_authority[0].data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name, "--region", var.aws_region]
    command     = "aws"
  }
}
```
**Code:**
```
        KubernetesProvider.Builder.create (this, "kubernetes")
                .host (clusterInformationDTO.getClusterEndPoint ())
                .clusterCaCertificate (Fn.base64decode (clusterInformationDTO.getClusterCA ()))
                .exec (KubernetesProviderExec.builder ()
                        .apiVersion ("client.authentication.k8s.io/v1alpha1")
                        .args (List.of ("eks", "get-token", "--cluster-name", clusterInformationDTO.getClusterName ()))
                        **.command** ("aws")
                        .build ())
                .build ();
```

**Here is my docker file:**
```
FROM ubuntu:20.04
RUN   apt-get update && \
      apt-get install -y curl && \
      apt-get install -y software-properties-common && \
      add-apt-repository -y ppa:linuxuprising/java && \
      apt-get update -y && \
      echo oracle-java17-installer shared/accepted-oracle-license-v1-3 select true | /usr/bin/debconf-set-selections && \
        apt-get install -y oracle-java17-installer oracle-java17-set-default && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /var/cache/oracle-java17-installer
ENV JAVA_HOME /usr/lib/jvm/java-17-oracle
RUN apt-get update -y && apt-get install maven -y
RUN mvn -version

RUN curl -s https://deb.nodesource.com/setup_16.x | bash
RUN apt-get -y install nodejs
RUN node -v

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt-get update -y
RUN apt-get install terraform

RUN apt-get update && apt-get install -y nocache git ca-certificates && update-ca-certificates
RUN apt-get install awscli -y

RUN apt-get upgrade -y

COPY command.sh /
CMD ["chmod","+x","command.sh"]

RUN mkdir /app
COPY target/*.jar /app/app.jar

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT exec java -jar /app/app.jar

```

i am using this same codebase using cdktf aws and kubernetes terraform provider. when i run this code from local machine its work perfectly but when i run this in docket container...its can not able to fetch token and throwing error. can you tell me how can i fix this issue ?

**Comment by arybolovlev** [comment] 2022-03-10 13:22
Closing this issue as a duplicate of https://github.com/hashicorp/terraform-provider-kubernetes/issues/1630.

**Closed by arybolovlev** 2022-03-10 13:22 UTC
Labels: question
