### ISSUE TITLE
Provider Option for `kube_config_raw`

### ISSUE THREAD

**Issue by DaleyKD** [hashicorp/terraform-provider-kubernetes#1817] opened 2022-08-26 18:32 UTC
### Description
AKS 1.24 started returning `exec` in its `kube_config_raw` property. Previously, we would configure the provider as follows:

``` hcl
provider "kubernetes" {
  host                   = module.aks_cluster.kube_config.host
  client_certificate     = base64decode(module.aks_cluster.kube_config.client_certificate)
  client_key             = base64decode(module.aks_cluster.kube_config.client_key)
  cluster_ca_certificate = base64decode(module.aks_cluster.kube_config.cluster_ca_certificate)
}
```

or if I wrote the raw out to a file:
``` hcl
provider "kubernetes" {
  config_path = "../../path/to/kubeconfig"
}
```

### Potential Terraform Configuration
While I understand that the `kubernetes` provider offers an `exec` block, it would be helpful if you would allow us to just pass in the raw config.

```hcl
provider "kubernetes" {
  config_raw = module.aks_cluster.kube_config_raw
}
```

### References
In `provider.go`, it seems like you could just condition on the raw (and it would have to conflict with the `config_path`/`config_paths`), to parse it?  I've never written anything in Go. Sorry.

What prompted this request is https://github.com/hashicorp/terraform-provider-azurerm/issues/18139#issuecomment-1228767463

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment] 2022-08-31 16:14
Hello! Thank you for opening this issue, this is a duplicate of [this issue](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1735). Please add a reaction to the duplicate issue.

**Closed by BBBmau** 2022-08-31 16:14 UTC
Labels: enhancement
