### ISSUE TITLE
Error: The terraform-provider-kubernetes_v2.7.1_x5 plugin crashed!

### ISSUE THREAD

**Issue by rmalenko** [hashicorp/terraform-provider-kubernetes#1557] opened 2021-12-30 08:25 UTC
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.1.2
Kubernetes provider version: 2.7.1
Kubernetes version: 1.21
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "ingress_istio_system_test_alb" {
  manifest = {
    "apiVersion" = "extensions/v1beta1"
    "kind"       = "Ingress"
    "metadata" = {
      "annotations" = {
        "alb.ingress.kubernetes.io/actions.ssl-redirect" = "{\"Type\": \"redirect\", \"RedirectConfig\": { \"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
        "alb.ingress.kubernetes.io/certificate-arn"      = "arn:aws:acm:us-east-1:7141585721:certificate/159834-fu3b-4e67-b283-715e445bd60e"
        "alb.ingress.kubernetes.io/listen-ports"         = "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
        "alb.ingress.kubernetes.io/load-balancer-name"   = "test-alb-victoriametrics"
        "alb.ingress.kubernetes.io/scheme"               = "internet-facing"
        "alb.ingress.kubernetes.io/tags"                 = "Environment=dev,Team=test"
        "external-dns.alpha.kubernetes.io/hostname"      = "jazzfest.link"
        "kubernetes.io/ingress.class"                    = "alb"
      }
      "name"      = "test-alb"
      "namespace" = "istio-system"
    }
    "spec" = {
      "rules" = [
        {
          "http" = {
            "paths" = [
              {
                "backend" = {
                  "serviceName" = "ssl-redirect"
                  "servicePort" = "use-annotation"
                }
                "path" = "/*"
              },
              {
                "backend" = {
                  "serviceName" = "istio-ingressgateway"
                  "servicePort" = 80
                }
                "path" = "/*"
              },
            ]
          }
        },
      ]
    }
  }
}
```

### Debug Output
https://gist.github.com/rmalenko/1a7b730008c0c2d96f79a372d4413d01

### Panic Output
panic: lists must only contain one type of element, saw tftypes.Object["backend":tftypes.Object["resource":tftypes.Object["apiGroup":tftypes.String, "kind":tftypes.String, "name":tftypes.String], "serviceName":tftypes.String, "servicePort":tftypes.String], "path":tftypes.String, "pathType":tftypes.String] and tftypes.Object["backend":tftypes.Object["resource":tftypes.Object["apiGroup":tftypes.String, "kind":tftypes.String, "name":tftypes.String], "serviceName":tftypes.String, "servicePort":tftypes.Number], "path":tftypes.String, "pathType":tftypes.String]

### Steps to Reproduce
1. `terraform plan`

**Comment by artm** [comment] 2022-02-09 12:57
this is a duplicate of https://github.com/hashicorp/terraform-provider-kubernetes/issues/1359

**Comment by arybolovlev** [comment] 2022-03-30 16:41
Hi @rmalenko,

Could you please verify if the issue is resolved with `v.2.8.0`?

Thank you.

**Comment by arybolovlev** [comment] 2022-03-31 11:06
Hi @rmalenko,

I've tested your code against `v2.8.0` and `v2.9.0` -- it seems to work with no issues. I will go ahead and close this issue, please feel free to reopen it if the issue still presents.

Thank you!

**Closed by arybolovlev** 2022-03-31 11:06 UTC
Labels: bug, crash
