### ISSUE TITLE
AKS - dial tcp [::1]:80: connect: connection refused on all plans modifying the azurerm_kubernetes_cluster resource

### ISSUE THREAD

**Issue by jamurtag** [hashicorp/terraform-provider-kubernetes#1307] opened 2021-06-11 15:45 UTC
Please see [this comment](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1307#issuecomment-873089000) for the explanation of the root cause. 

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.15, 1.0
Kubernetes provider version: 2.3.0
Kubernetes version: 1.19
```

### Affected Resource(s)

- all resources

### Terraform Configuration Files
Our configuration is almost identical to your [aks example](https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/aks) code, so I tried using that and replicated the behaviour.

Note - I simulated by modifying the **workers_count** variable in the `aks-cluster` directory, however this isn't actually implemented in your code. Modify [line 23](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_examples/aks/aks-cluster/main.tf#L23) to be `node_count = var.workers_count`, then pass a new value in via the aks-cluster module in main.tf.

### Steps to Reproduce
1. Update the `aks-cluster` module as directed above to support **workers_count**
2. `terraform apply`
3. Change the **workers_count** variable to any other value
4. `terraform plan`

### Expected Behavior
Terraform should display a plan showing the updated node pool count.

### Actual Behavior
The following error is reported:

```hcl
$ terraform plan
random_id.cluster_name: Refreshing state... [id=aE_9C3A]
module.aks-cluster.azurerm_resource_group.default: Refreshing state... [id=/subscriptions/ff83a9d2-8d6e-4c4a-8b34-641163f8c99f/resourceGroups/tf-k8s-684ffd0b70]
module.aks-cluster.azurerm_kubernetes_cluster.default: Refreshing state... [id=/subscriptions/ff83a9d2-8d6e-4c4a-8b34-641163f8c99f/resourcegroups/tf-k8s-684ffd0b70/providers/Microsoft.ContainerService/managedClusters/tf-k8s-684ffd0b70]
module.kubernetes-config.local_file.kubeconfig: Refreshing state... [id=1ca8ad3c1c7f4aff65e5eda0038b619788b0956a]
module.kubernetes-config.helm_release.nginx_ingress: Refreshing state... [id=nginx-ingress-controller]
module.kubernetes-config.kubernetes_namespace.test: Refreshing state... [id=test]
╷
│ Error: Get "http://localhost/api/v1/namespaces/test": dial tcp [::1]:80: connect: connection refused
│
│   with module.kubernetes-config.kubernetes_namespace.test,
│   on kubernetes-config/main.tf line 14, in resource "kubernetes_namespace" "test":
│   14: resource "kubernetes_namespace" "test" {
│
╵
╷
│ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
│
│   with module.kubernetes-config.helm_release.nginx_ingress,
│   on kubernetes-config/main.tf line 59, in resource "helm_release" "nginx_ingress":
│   59: resource helm_release nginx_ingress {
```

The data source is clearly not passing back valid data, even though there is a dependency on the aks-cluster module.

**Comment by chakri-nelluri** [comment] 2021-06-11 21:06
I am hitting the same issue.
```
 2021-06-11T16:51:39.576-0400 [DEBUG] plugin: using plugin: version=5
 8675 2021-06-11T16:51:39.640-0400 [INFO]  plugin.terraform-provider-kubernetes_v2.3.2_x5: 2021/06/11 16:51:39 [WARN] Invalid provider configuration was supplied. Provider operations likely to fail: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable: timestamp=2021-06-11T16:51:39.640-0400
 8676 2021-06-11T16:51:39.640-0400 [INFO]  plugin.terraform-provider-kubernetes_v2.3.2_x5: 2021/06/11 16:51:39 [DEBUG] Enabling HTTP requests/responses tracing: timestamp=2021-06-11      T16:51:39.640-0400
 ```

**Comment by thy143** [comment] 2021-06-28 11:45
We are also hitting this and it’s causing a bit of a headache

**Comment by dak1n1** [comment] 2021-07-02 15:39
Hi, I'm sorry to hear you all are struggling with this dependency issue. I've done extensive research in this area and come across similar scenarios. The cause has to do with [passing an unknown value to a provider configuration block](https://www.terraform.io/docs/language/providers/configuration.html#provider-configuration-1), which is not supported in Terraform core. To quote their docs:

```
You can use expressions in the values of these configuration arguments, 
but can only reference values that are known before the configuration is applied.
```

When you make a change to the underlying infrastructure, such as node count, you're passing an unknown value into the Kubernetes provider configuration block, since the full scope of the cluster infrastructure is not known until after the change has been applied to the AKS cluster. That's why Terraform is behaving as if it's not reading the cluster's data source properly.

Although I did write the initial guide to show that [it can be possible to work around some of these issues](https://github.com/hashicorp/terraform-provider-kubernetes/tree/614b5ed8ab2e962df855c0c8d4ca9c7ec50e88fe/_examples/aks#replacing-the-aks-cluster-and-re-creating-the-kubernetes--helm-resources), as you've found from experience, there are many edge cases that make it an unreliable and unintuitive process, to get the Kubernetes provider working alongside the underlying infrastructure. This is due to a long-standing  [limitation in Terraform](https://github.com/hashicorp/terraform/issues/4149), that can't be fixed in any provider, but we do have plans to smooth out the bumps a little by adding [better error messages upfront](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1141), so that users don't run into this on subsequent applies.

I thought at first that I could list out every work-around to help users keep their preferred workflow of having the cluster in the same Terraform state as the Kubernetes resources. Most cases can be worked around using `terraform state rm module.kubernetes-config` or `terraform apply -target=module.aks-cluster`, but I think encouraging this kind of work-around will cause more headaches in the long run, as it puts the user in charge of figuring out when to use special one-off apply commands, rather than setting up Terraform to behave reliably and predictably from the start. Plus it can have unintended side-effects, like [orphaning cloud resources](https://github.com/hashicorp/terraform/issues/27728#issuecomment-840093064).

That's why I have a new guide in progress here, which shows the most reliable method that we have so far: the cluster infrastructure needs to be kept in a state separate from the Kubernetes and Helm provider resources.

https://github.com/hashicorp/terraform-provider-kubernetes/tree/e058e225e621f06e393bcb6407e7737fd43817bd/_examples/aks

I know this is inconvenient, which is why we continue to try and accommodate users in single-apply scenarios, and scenarios which contain the Kubernetes and cluster resources in the same Terraform state. However, until upstream Terraform can add support for this, the single-apply workflow will remain buggy and less reliable than separating cluster infrastructure from Kubernetes resources.

**Comment by pmnathan** [comment] 2021-09-21 13:41
I have been testing using an alias azure provider for the data query and this seems to resolve the issue. More testing is obviously required...from Steph's code example (https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_examples/aks/main.tf)  the change will look like 

`
provider "azurerm" {
  alias = "azurerm_k8s"
  features {}
}

data "azurerm_kubernetes_cluster" "default" {
  provider            = azurerm.azurerm_k8s
  depends_on          = [module.aks-cluster] # refresh cluster state before reading
  name                = local.cluster_name
  resource_group_name = local.cluster_name
}
`

**Comment by stevehipwell** [comment] 2021-10-21 15:36
@dak1n1 this error message is unintuitive as it isn't explaining why the error is occurring and leads to significant lost time tracking down the cause. Furthermore, if the error here is correct it means that Terraform has attempted to connect to the localhost cluster, which could have unintended consequences if there is such a cluster.

**Comment by BoHuang2018** [comment] 2021-11-02 13:39
I encountered same problem on GKE @dak1n1 `terraform state rm -target modules.my-gke-module`  ` terraform plan -target modules.my-gke-module`  `terraform apply -target modules.my-gke-module`  helped to fix my problem. Thanks. I will try your new guide with GKE

**Comment by sgutwein** [comment] 2021-11-22 15:29
Also adapted the node count, the first apply went through without problems. Now I 'm facing the same error message on every plan / apply...
`Error: Get "http://localhost/api/v1/namespaces/external-secrets": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_namespace.namespaces["external-secrets"],
│   on main.tf line 109, in resource "kubernetes_namespace" "namespaces":
│  109: resource "kubernetes_namespace" "namespaces" {
`

**Comment by BoHuang2018** [comment] 2021-11-22 15:36
Hi @sgutwein ,  I used methods of @dak1n1  to solve my error on GKE successfully. I guess it's a solution to your error.

**Comment by sgutwein** [comment] 2021-11-23 15:51
@BoHuang2018 It was a lot of pain, but that fixed it. Thanks.

**Comment by favoretti** [comment] 2021-12-14 19:32
Running `terraform apply -refresh=false` will just silently do the right thing BTW, as it won't try to refresh the current state. (And in general since this only happens when cluster gets recreated - no refresh isn't as bad as it sounds).

**Comment by arlepep** [comment] 2021-12-21 11:37
thanks @favoretti  for your answer . it works for me.

**Comment by josephcaxton** [comment] 2022-01-15 14:14
@dak1n1 thanks for that explaination. It realy helped

**Comment by holms** [comment] 2022-01-18 04:19
Can someone please explain what is going on :)?

```
# NOTE: the Name used for Redis needs to be globally unique
resource "azurerm_redis_cache" "setupad_prebid_cache" {
  name                = "setupad-prebid-cache"
  location            = azurerm_resource_group.prebid.location
  resource_group_name = azurerm_resource_group.prebid.name
  capacity            = 2
  family              = "C"
  sku_name            = "Basic"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  redis_configuration {
  }
}

# Use data source as workaround because asking outputs directly makes terraform kubernetes provider
# fall to localhost for some reason. It's a known issue on github.

data "azurerm_redis_cache" "setupad_prebid_cache" {
  name                = "setupad-prebid-cache"
  resource_group_name = azurerm_resource_group.prebid.name
}


resource "kubernetes_secret" "prebid_cache_redis" {
  metadata {
    name      = "prebid-cache-redis"
    namespace = "prebid"
  }
  data = {
    host     = data.azurerm_redis_cache.setupad_prebid_cache.hostname
    port     = data.azurerm_redis_cache.setupad_prebid_cache.ssl_port
    password = data.azurerm_redis_cache.setupad_prebid_cache.primary_access_key
  }
  depends_on = [azurerm_redis_cache.setupad_prebid_cache]
}
```

Then I have IMHO error

```
kubernetes_secret.prebid_cache_redis: Creating...
╷
│ Error: Post "http://localhost/api/v1/namespaces/prebid/secrets": dial tcp [::1]:80: connect: connection refused
│ 
│   with kubernetes_secret.prebid_cache_redis,
│   on azure-redis.tf line 25, in resource "kubernetes_secret" "prebid_cache_redis":
│   25: resource "kubernetes_secret" "prebid_cache_redis" {
```

**Comment by xelhark** [comment] 2022-01-20 16:40
A better fix for GKE that worked for me was [let google handle the connection config](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry) in `~/.kube/config` and feed the kube config file to the provider manually:

```sh
gcloud container clusters get-credentials <my_cluster> --region=<my_region>
```

```hcl
provider "kubernetes" {
  cluster_ca_certificate = base64decode(google_container_cluster.main.master_auth.0.cluster_ca_certificate)
  host                   = "https://${google_container_cluster.main.endpoint}"
  token                  = data.google_client_config.current.access_token
  config_path    = "~/.kube/config"
}
```

**Comment by jrhouston** [comment] 2022-02-23 17:34
As @dak1n1 explained [above](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1307#issuecomment-873089000) this is due to progressive apply. Please open a new issue with your complete configuration if you feel you are encountering a different issue than the original issue reported here.

**Closed as completed by jrhouston** 2022-02-23 17:34 UTC
Labels: bug, upstream-terraform, theme/auth, progressive apply
