### ISSUE TITLE
Support StorageClass allowedTopologies and volumeBindingMode fields

### ISSUE THREAD

**Issue by avthart** [hashicorp/terraform-provider-kubernetes#891] opened 2020-06-22 09:33 UTC
### Description

We would like to create additional storage classes on Google Cloud. Therefore we need to set 
`allowedTopologies` and `volumeBindingMode` fields which is currently not possible.

See:

* https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
* https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

### Potential Terraform Configuration

See examples on Kubernetes.io website.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DrFaust92** [comment] 2020-07-13 12:45
duplicate of #391

**Comment by dak1n1** [comment] 2021-05-16 17:46
Closing since this feature has been released.

**Closed by dak1n1** 2021-05-16 17:46 UTC
Labels: acknowledged, enhancement, help wanted, theme/coverage
