### ISSUE TITLE
Add support for pathType on kubernetes_ingress

### ISSUE THREAD

**Issue by mosheavni** [hashicorp/terraform-provider-kubernetes#1101] opened 2020-12-24 20:43 UTC
### Description
The ingress resource contains new fields such as `pathType` and in general a different scheme

### Potential Terraform Configuration

```hcl
resource "kubernetes_ingress" "my_ingress" {
  metadata {
    name = "ingress-resource-backend"
  }
  spec {
    defaultBackend {
      resource = {
        "apiGroup" = "k8s.example.com"
        "kind"     = "StorageBucket"
        "name"     = "static-assets"
      }
    }
    rule {
      http {
        paths {
          backend {
            resource {
              apiGroup = "k8s.example.com"
              kind     = "StorageBucket"
              name     = "icon-assets"
            }
          }
          path     = "/icons"
          pathType = "ImplementationSpecific"
        }
      }
    }
  }
}
```
This is probably whole wrong but I think you get the point

### References
https://kubernetes.io/docs/concepts/services-networking/ingress/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment] 2021-01-20 17:33
Dupe of #1023

**Closed by aareet** 2021-01-20 17:33 UTC
Labels: enhancement
