### ISSUE TITLE
Data Source `kubernetes_resources` Crashes Provider Plugin

### ISSUE THREAD

**Issue by jann-erhardt-meso** [hashicorp/terraform-provider-kubernetes#2365] opened 2023-12-11 08:32 UTC
Hey there,
My Kubernetes Provider Configuration Crashes, when trying to get Pods from a namespace using the `kubernetes_resources` Data Source, any Ideas why?

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.6.5
Kubernetes provider version: 2.24.0
Kubernetes version: 1.28
```

### Affected Resource(s)

- data kubernetes_resources

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.5"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.24.0"
    }
  }
}

data "kubernetes_resources" "kube_system_pods" {
  api_version    = "v1"
  kind           = "Pod"
  namespace      = "kube-system"
}
```

### Debug Output

https://gist.github.com/jann-erhardt-meso/582a33ca06aea5ec4615e39e81744d55

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

It is a completly terraform Managed EKS Cluster running on Managed Node Groups. Plus Network access is working and the User has enough rights.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mathportillo** [comment] 2023-12-14 03:07
I have the exact same error with the exact same stacktrace (linked in OP debug ouput) when querying by Deployments

```
data "kubernetes_resources" "kube_system_deployments" {
  api_version = "apps/v1"
  kind              = "Deployment"
  namespace = "kube-system"
}
```

I also tried deployments from other namespaces besides kube-system with the same results
I also tried terraform-provider-kubernetes versions 1.18, 1.23 and 1.24 with the same results

**Comment by sheneska** [comment] 2023-12-18 15:04
Hi, @jann-erhardt-meso thank you for opening this issue. It is a duplicate of issue #2215,  to help us prioritize our efforts, please upvote this issue by giving a thumbs up. I will go ahead and close this issue for now.

**Closed by sheneska** 2023-12-18 15:04 UTC
Labels: bug
