### ISSUE TITLE
Pod metadata not inherited from parent deployment

### ISSUE THREAD

**Issue by seuf** [hashicorp/terraform-provider-kubernetes#616] opened 2019-09-12 09:44 UTC
### Terraform Version
v0.11.14

### Affected Resource(s)
deployments

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "whoami" {
  metadata {
    name      = "whoami"
    namespace = "${kubernetes_namespace.whoami.metadata.0.name}"

    labels {
      app = "whoami"
    }
  }

  spec {
    replicas = "1"

    selector {
      match_labels = {
        app = "whoami"
      }
    }

    template {
      metadata {
        labels {
          app  = "whoami"
        }
      }

      spec {
        container {
          image = "containous/whoami"
          name  = "whoami"

          port {
            name           = "http"
            container_port = 80
            protocol       = "TCP"
          }
        }
      }
    }
  }
}
```

### Debug Output
When I do a terraform plan the resource which was **previously created and imported in state** is changed :

```
spec.0.template.0.metadata.0.namespace:   "" => "default" (forces new resource)
```

### Expected Behavior
The namespace in the pod template should be inherited from the parent resource (deployment)
Or empty if already defined in the parent.

### Actual Behavior
resource is recreated and the pod is running in the deployment namespace (not default)
Is it normal ?
maybe the default value for `namespace` in namespacedMetada should be `""` instead of `"default"` ?

**Comment by seuf** [comment] 2019-09-13 07:28
OK, I didn't see that, sorry.

**Comment by flmmartins** [comment] 2019-11-01 15:19
WoW this is huge I think it's causing a bug one of my deployments! Thanks for the PR @pdecat!!
Please can someone approve this?? Please!!

**Comment by flmmartins** [comment] 2019-11-06 13:25
The PR got merged so when it's going to be released?

**Comment by alexsomesan** [comment] 2019-11-06 15:47
I'll cut a release before the end of the week.

**Comment by odedpriva** [comment] 2020-03-10 08:57
any idea why this was not merged ?

**Comment by pdecat** [comment] 2020-03-10 11:49
Hi @odedpriva, would you mind sharing your resource's terraform configuration and the exact plan you're seing?

**Comment by alexsomesan** [comment] 2020-09-09 15:53
I cannot reproduce this issue anymore. Closing.

**Closed** 2020-11-18 06:58 UTC
Labels: bug
