### ISSUE TITLE
Kubernetes provider 2.7.1 (Linux x86-64) crashes with AWS EKS while applying Prometheus CRD ServiceMonitor

### ISSUE THREAD

**Issue by izinovik** [hashicorp/terraform-provider-kubernetes#1585] opened 2022-01-26 16:01 UTC
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.1.14 (linux_amd64)
Kubernetes provider version: 2.7.1
Kubernetes version: AWS EKS v1.21.5-eks-bc4871b
```

### Affected Resource
- `module.gitlab.kubernetes_manifest.gitlab-metrics-servicemonitor[0]`

### Debug Output
https://gist.github.com/izinovik/832bb4a1c397837ea605a72424bab526

### Panic Output

https://gist.github.com/izinovik/7132298c24d5f4673abae8308099eb02

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior

Terraform should apply plan without crashing.

### Actual Behavior

Terraform kubernetes provider crashed.

**Comment by izinovik** [comment] 2022-01-26 16:03
Here is a resource that I'm trying to apply:
```
resource "kubernetes_manifest" "gitlab-metrics-servicemonitor" {
  count = var.gitlab_metrics_enabled ? 1 : 0

  manifest = {
    apiVersion = "monitoring.coreos.com/v1"
    kind       = "ServiceMonitor"
    metadata = {
      name      = "${var.name}-gitlab-metrics"
      namespace = kubernetes_namespace.gitlab.0.metadata.0.name
      labels = merge(
        module.this.kubernetes_labels
      )
    }
    spec = {
      selector = {
        matchLabels = {
          release = var.name
        }
      }
      namespaceSelector = {
        matchNames = [kubernetes_namespace.gitlab.0.metadata.0.name]
      }
      endpoints = [
        {
          # GitLab exporter /metrics
          port = "gitlab-exporter"
          path = "/metrics"
        },
        {
          # Redis exporter
          port = "metrics"
          path = "/metrics"
        },
        {
          # GitLab webservice metrics (rails)
          port = "http-webservice"
          path = "/-/metrics"
        },
        {
          # GitLab http metrics (puma)
          port = "http-exporter"
          path = "/metrics"
        },
        {
          # GitLab workhorse metrics
          port = "http-workhorse-exporter"
          path = "/metrics"
        },
        {
          # GitLab gitaly metrics
          targetPort = "9236"
          path       = "/metrics"
        }
      ]
    }
  }
}
```

**Comment by alexsomesan** [comment] 2022-02-09 13:18
Hi!

I was able to reproduce this with provider version 2.7.1
We have just recently merged the fix for this issue and it should go out in the next release, in the next day or two.

I've also tried to reproduce with a provider build from main and can confirm that the issue is gone.

**Comment by alexsomesan** [comment] 2022-02-09 17:15
Closing. Please re-open if it persists after the upcoming provider release.

**Closed by alexsomesan** 2022-02-09 17:15 UTC
