### ISSUE TITLE
kubernetes_config_map_v1 does not support immutable attribute

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform-provider-kubernetes#1842] opened 2022-09-23 08:26 UTC
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: latest
Kubernetes provider version: latest
Kubernetes version: latest
```

### Affected Resource(s)

- kubernetes_config_map_v1

### Terraform Configuration Files
```hcl
resource "kubernetes_config_map_v1" "default" {
  metadata {
    name = "prometheus"
    namespace = var.namespace.metadata[0].name
  }

  immutable = true # Not supported
}
```

### Expected Behavior
It should support the attribute.

### Actual Behavior
It does not.

### References

- https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment] 2022-09-28 16:20
Thank you for bringing up this issue! We'll be closing this since this is a duplicate of #1317

**Closed by BBBmau** 2022-09-28 16:20 UTC
