### ISSUE TITLE
Bug: limits & secrets are not recreated

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-kubernetes#776] opened 2020-02-27 09:57 UTC
### Terraform Version
0.12

### Affected Resource(s)
- kubernetes_secret
- kubernetes_limit_range

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
```
 2020/02/27 09:47:38 [ERROR] module.kubernetes: eval: *terraform.EvalApplyPost, err: Failed to update secret: secrets "se-github-mainwebsite-deploy" not found
2020/02/27 09:47:38 [ERROR] module.kubernetes: eval: *terraform.EvalSequence, err: Failed to update secret: secrets "se-github-mainwebsite-deploy" not found
2020/02/27 09:47:38 [ERROR] module.kubernetes: eval: *terraform.EvalApplyPost, err: Failed to update limit range: limitranges "default-resource-limitations" not found
2020/02/27 09:47:38 [ERROR] module.kubernetes: eval: *terraform.EvalSequence, err: Failed to update limit range: limitranges "default-resource-limitations" not found

Error: Failed to update limit range: limitranges "default-resource-limitations" not found

  on modules/kubernetes/limits.tf line 2, in resource "kubernetes_limit_range" "default-resource-limitations":
   2: resource "kubernetes_limit_range" "default-resource-limitations" {



Error: Failed to update secret: secrets "se-github-mainwebsite-deploy" not found

  on modules/kubernetes/ns-mainwebsite.tf line 39, in resource "kubernetes_secret" "se_github_mainwebsite_deploy":
  39: resource "kubernetes_secret" "se_github_mainwebsite_deploy" {
```

### Expected Behavior
Secrets & limits are recreated if not found.

### Actual Behavior
Secrets & limits return 'not found'

### Steps to Reproduce
1. `terraform apply`
2. Destroy kubernetes cluster physically
3. `terraform apply`

**Comment by aareet** [comment] 2020-09-02 19:16
@hazcod is this still reproducible for you with the latest version? Can you post logs with TRACE enabled?

**Comment by aareet** [comment] 2020-09-24 19:33
Closing since it has been a few weeks. Please reopen if this is still an issue.

**Closed by aareet** 2020-09-24 19:33 UTC
Labels: bug, waiting-response
