### ISSUE TITLE
Kubernetes Provider 1.11.3 "Unauthorized"

### ISSUE THREAD

**Issue by privomark** [hashicorp/terraform-provider-kubernetes#918] opened 2020-07-16 17:58 UTC
### Terraform Version and Provider Version
Terraform v0.12.26
+ provider.archive v1.3.0
+ provider.aws v2.70.0
+ provider.helm v1.2.3
+ provider.kubernetes v1.11.3
+ provider.null v2.1.2

### Affected Resource(s)
- kubernetes_cluster_role

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  version                = "1.11.3"
  host                   = aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  #config_context         = aws_eks_cluster.cluster.arn
  load_config_file       = false
}
```

```hcl
resource "kubernetes_cluster_role" "admin_role" {
  metadata {
    name = "k8s-admin-role"
    labels = {
      name = "AdminRole"
    }
  }

  rule {
    api_groups = ["", "apps", "batch", "extensions"]
    resources = [
      "pods", "cronjobs", "deployments", "devents", "ingresses",
      "jobs", "pods/attach", "pods/exec", "pods/log", "pods/portfoward",
      "secrets", "services", "nodes"
    ]
    verbs = [
      "get", "list", "watch", "delete", "describe", "patch",
    "update", "create"]
  }

  depends_on = [aws_eks_node_group.cluster_node_group]
}
```

### Expected Behavior
What should have happened?
`Apply complete!`

Terraform should create my cluster, node group and cluster role successfully.

### Actual Behavior
```
Error: Unauthorized

  on ../../modules/eks/rbac.tf line 35, in resource "kubernetes_cluster_role" "admin_role":
  35: resource "kubernetes_cluster_role" "admin_role" {
```

Works properly 2nd time running `terraform apply`

### Steps to Reproduce
1. `terraform apply` --> Fails
2. `terraform apply` --> Works 2nd Time (no changes between commands)

### Important Factoids

- Running k8s provider v1.9 works on initial run, but when running `terraform destroy` I get an error against the `kubernetes_cluster_role` saying `system:anonymous` does not have access to destroy.
  - If I change the provider to `load_config_file = false` and use the `config_context`, then it works. But this method does not work on `terraform apply`. I have to manually switch each time I want to do a destroy.

### References

- #679 

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by holms** [comment] 2020-07-22 00:05
This problem appeared today, although I've haven't done `terraform init` for like a week already. Also downgrading up to 3 versions back didn't help it either, so I guess maybe it's a problem with Digital ocean? Although my `kubectl` works well locally.

**Comment by Vlaaaaaaad** [comment] 2020-07-29 11:43
EKS tokens need to be refreshed every 15 minutes. If a Terraform apply runs and takes longer than 15 minutes, we get this error. A re-plan and re-apply works without issue.

What's weird is that we sometimes also get this error on a simple change that takes less than 15 minutes, like changing a value in a `ConfigMap`. Re-plan and re-apply also work here, so it's not a credential/ AWS IAM issue.

**Comment by djakielskiadesso** [comment] 2020-08-04 22:21
It would be nice if you could make the error message (Unauthorized) clearer. At the moment we can only guess that this is a Kubernetes problem. There is no more context surround this error message. No message like stacktrace or on resource ...

Just:
![grafik](https://user-images.githubusercontent.com/52488859/89350797-f61e7200-d6b0-11ea-8880-f304c04467c8.png)

My Versions:
Terraform 1.12.28
Kubernets Provider 1.12
Kubernetes API 1.17

Proposal: Could not connect to kubernetes api (https://api.k8s.de), Authorization failed. Please check your credentials.

**Comment by holms** [comment] 2020-08-05 00:04
My bad. This is actually unauthorised into k8s cluster. Problem is that I'm using creds from another state, I've split infra and post-infra projects, and grabbing k8s creds from output which is masked. Seems to me token been expired, when I've did terraform apply in the first project, second one started to work. Interestingly I've never had this issue before. Seems to me digital ocean decreased token lifetime maybe. Hope this experience will help someone.

**Comment by assafcoh** [comment] 2020-09-10 06:18
we also encounter this "Error: Unauthorized" after updating our k8s cluster to new kubernetes version because this takes more than 15 minutes.
It would be great if the Kubernetes Provider could automatically refresh an expired token and continue without errors.

**Comment by Carles-Figuerola** [comment] 2020-09-17 20:00
Having this same problem when EKS upgrades take longer than 15 minutes. I think that using a kubeconfig file instead of supplying the token to the provider this way `token = data.aws_eks_cluster_auth.cluster.token` fixes it as for every kubectl call, a new token is requested. However, I have not confirmed this 100%.

One other option I thought is creating a second provider for post-upgrade usage by aliasing, but I believe that all providers are initialized at the same time so the tokens would expire at the same time: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations

A solution that doesn't expect the kubeconfig to be set up before the provider runs and that auto-renews the token would be greatly appreciated

**Comment by yardensachs** [comment] 2020-09-23 20:48
It seems to be an issue that I would need to apply some change first, to be able to run something like `terraform import`.
I had to add some resource with missing information so it would fetch the token but fail the apply.
Any better solutions?

**Comment by Monkman08** [comment] 2020-10-28 09:57
> It seems to be an issue that I would need to apply some change first, to be able to run something like `terraform import`.
> I had to add some resource with missing information so it would fetch the token but fail the apply.
> Any better solutions?

This is the exact thing i am seeing with the latest provider. Trying to import without an apply first (so far its only affecting clusterrolebindings and clusterroles)

once i apply something else first, im then able to complete the import.

**Comment by sosimon** [comment] 2020-12-16 04:46
Very weird. I just experienced the same thing - `Error: unauthorized` - when trying to `terraform import` a resource from an EKS cluster.

I ran a `terraform apply` (0 diffs! i.e. `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`), and then tried the import again and it worked.

**Comment by adrianmiron** [comment] 2020-12-31 11:22
I am having the same issues on EKS with 1.13.3 ( did not have this issue with 1.10.x) when deleting configmaps/secrets  as part of a big plan which includes a lot of non EKS stuff( i assume the token is requested at the start but by the time it gets to using it it's expired; if doing targeted deletes it works fine). I can also confirm the issue is inconsistent, doing the same plan a few times ( create/delete) it appears about 50% if the times.

Would be great if a fix would be included in future versions, cheers.

**Comment by ghassencherni** [comment] 2021-02-02 08:57
Still reproduced with 1.14

**Comment by iarlyy** [comment] 2021-02-26 08:39
Experiencing the same with the following stack:

- EKS K8s v1.19
- Terraform v0.14.5
- Kubernetes Provider v2.0.2 (should we have another ticket?)


```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.k8s_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.k8s_cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.k8s_cluster.token
}
```

**Comment by iarlyy** [comment] 2021-02-26 09:25
This worked for me (using the same provider config above):

Added the role that is being used by the pod to the aws-auth configmap.

```
    - rolearn: arn:aws:iam::**account_id**:role/terraform-runner-role
      username: admin:{{SessionName}}
      groups:
        - system:masters
```

**Comment by fenethtool** [comment] 2021-03-04 02:45
Still reproduced with 1.18.

As a temporary fix, I was able to update the token by regenerating the statefile using the `terraform refresh` command, which avoided this problem.

I hope that you will implement a process to automatically update the token when creating and building kubernetes-related resources.

**Comment by rmasclef** [comment] 2021-03-05 22:18
> Still reproduced with 1.18.
> 
> As a temporary fix, I was able to update the token by regenerating the statefile using the `terraform refresh` command, which avoided this problem.
> 
> I hope that you will implement a process to automatically update the token when creating and building kubernetes-related resources.

I can add the fact that Terraform-cloud users don't have the possibility to to this workaround unless they declare a `backend` in tf code in order to be able to perf tf actions using cli instead of tfCloud interface.

**Comment by Cajga** [comment] 2021-04-20 14:50
Hi Guys,

Seems the recommended way to use the kubernetes provider for EKS is to use exec instead of token due to the short living token for AWS [more info in the official documentation](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins): 

> Some cloud providers have short-lived authentication tokens that can expire relatively quickly. To ensure the Kubernetes provider is receiving valid credentials, an exec-based plugin can be used to fetch a new token before initializing the provider.

At the same time as we are running the config in CI/CD (gitlab) we did not want to have a full blown aws cli (version 2 requires proper glibc which is of course not available in alpine images and it is also few 100MB) in our terraform image so, I developed a very simple go code that can be built into a single static binary (and is 13MB) and can be used by the exec call of the kubernetes provider. You can find it here: [terraform-kubernetes-provider-eks-exec-plugin](https://github.com/Cajga/terraform-kubernetes-provider-eks-exec-plugin)

**Comment by ipleten** [comment] 2021-04-20 23:55
I get such problem while trying to import kuberenets_secret:
```
kubernetes_secret.newrelic-license-key: Importing from ID "newrelic/newrelic-license-key"...
kubernetes_secret.newrelic-license-key: Import prepared!
  Prepared kubernetes_secret for import
kubernetes_secret.newrelic-license-key: Refreshing state... [id=newrelic/newrelic-license-key]

Error: Unauthorized
```

**Comment by stealthHat** [comment] 2021-05-24 11:53
Still reproduced with eks 1.20 and terraform 1.15. but the workarround that @ipleten post works for me

**Comment by jsun6383** [comment] 2021-06-02 04:42
@ipleten that is perfect. Given the token generated by `aws-iam-authenticator` have a short life. It would make sense creating a new token on every run would be the better solution.

**Comment by rootshell2** [comment] 2021-07-15 12:23
I ran into the same issue when I've tried to import the "kubernetes_secret" resource and it got solved simply running a "terraform refresh" before, FYI

**Comment by matheuss** [comment] 2021-08-05 19:56
@ipleten' workaround is a blessing – it will save my team hundreds of hours of `dang it, the apply failed because the EKS token expired – we gotta run the plan again`. Thank you @ipleten!

**Comment by iBrandyJackson** [comment] 2021-11-24 17:34
We are going to close this issue due to this being related to an outdated version. This helps our maintainers find and focus on the active and important issues. If you have found a problem that seems related to this issue, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.

**Closed by iBrandyJackson** 2021-11-24 17:34 UTC
Labels: bug, needs investigation, acknowledged
