### ISSUE TITLE
Delete Runtime-Class

### ISSUE THREAD

**Issue by romina2001** [hashicorp/terraform-provider-kubernetes#1216] opened 2021-03-29 14:04 UTC
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 0.14.4
Kubernetes Provider version: 2.0.3
Kubernetes version: AKS - 1.19.7
```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question
```
How would it be possible to do a "kubectl delete runtimeClass windows-2019" using Terraform?
This is how I am trying to do it but with no success:

resource "null_resource" "kubectl" {
  provisioner "local-exec" {
    interpreter = ["PowerShell", "-Command"]
    command = <<-EOT
      exec "az aks get-credentials -n ${azurerm_kubernetes_cluster.aks.name} -g ${azurerm_kubernetes_cluster.aks.resource_group_name} --admin"
      exec "kubectl delete runtimeClass windows-2019"
      EOT
}
  }


```

**Comment by jrhouston** [comment] 2021-04-07 06:21
This is a duplicate of https://github.com/hashicorp/terraform-provider-kubernetes/issues/1114

**Closed by jrhouston** 2021-04-07 06:21 UTC
Labels: question
