### ISSUE TITLE
new data type: tunnel (port forward)

### ISSUE THREAD

**Issue by geektheripper** [hashicorp/terraform-provider-kubernetes#2438] opened 2024-03-06 17:41 UTC
### Description

tunnel forward local port to specific kubernetes resource, like what `kubectl port-forward` do

it helps users to access services inside kubernetes, such as databases

### Potential Terraform Configuration

```hcl
data "kubernetes_tunnel" "postgresql" {
  namespace = "database"
  resource  = "deployment/postgresql-deployment"
  port      = 5432
}

provider "postgresql" {
  host = data.kubernetes_tunnel.postgresql.localhost
  port = data.kubernetes_tunnel.postgresql.localport
  # ......
}

data "kubernetes_tunnel" "minio" {
  namespace = "storage"
  resource  = "service/minio-service"
  port      = "http"
}

provider "minio" {
  minio_server = "${data.kubernetes_tunnel.minio.localhost}:${data.kubernetes_tunnel.minio.localport}"
  # ......
}

resource "minio_s3_bucket" "bililive_rec" {
  bucket = "bililive-rec"
  acl    = "public-read"
  quota  = 109951162777600
}
```

### References

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/portforward/portforward.go
https://github.com/flaupretre/terraform-ssh-tunnel

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment] 2024-03-11 05:59
Thanks for opening this @geektheripper. This is actually a duplicate of #812. Please [see my comment](https://github.com/hashicorp/terraform-provider-kubernetes/issues/812#issuecomment-1093060228) on that issue thread on why a port-foward/tunnel can't be created inside this provider, and that this is a problem that should be solved upstream in terraform itself.

**Closed by jrhouston** 2024-03-11 05:59 UTC
Labels: enhancement
