### ISSUE TITLE
kubernetes_ingress kubernetes v2.6.1 - Failed to create Ingress

### ISSUE THREAD

**Issue by Sw00shy** [hashicorp/terraform-provider-kubernetes#1492] opened 2021-11-11 09:37 UTC
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: Terraform v1.0.8
Kubernetes Provider version: registry.terraform.io/hashicorp/kubernetes v2.6.1
Kubernetes version: v1.22.3
```
## Terraform configuration
```hcl
resource "kubernetes_ingress" "jenkins-ingress" {
    metadata {
        name = "${var.name}-ingress"
        namespace = var.namespace
        annotations = {
            "ingress.kubernetes.io/rewrite-target" = "/"
            "kubernetes.io/ingress.class" = "nginx"
        }
    }
    spec {
        rule {
            host = "domain.com"
            http {
                path {
                    path = "/"
                    backend {
                        service_name = var.name
                        service_port = 8080
                    }
                }
            }
        }
   }
}
```

## Question
```
I try to create an ingress resource over terraform. I receive the following error message

> Error: Failed to create Ingress 'jenkins/jenkins-ingress' because: the server could not find the requested resource (post 
> ingresses.extensions) │ │ with kubernetes_ingress.jenkins-ingress, │ on main.tf line 160, in resource "kubernetes_ingress"
> "jenkins-ingress": │ 160: resource "kubernetes_ingress" "jenkins-ingress" {

What strikes me is the difference between **_rule_** and **_rules_** (see kubernetes_ingress) in the terraform script in compare to the yaml. Ideas?
```

**Comment by Skaronator** [comment] 2021-11-14 19:13
Just search in the issue tracker for `ingresses.extensions` and you'll find a couple issues and already a PR which adds support for Ingress v1 API.

Duplicate of #1386 and #1049

**Comment by alexsomesan** [comment] 2021-11-17 17:11
Closing as duplicate. Support for networking.k8s.io/v1 will come in the next provider release.

**Closed by alexsomesan** 2021-11-17 17:11 UTC
Labels: question
