### ISSUE TITLE
"Failed to morph manifest to OAPI type" on kubernetes_manifest resource

### ISSUE THREAD

**Issue by empeekdev** [hashicorp/terraform-provider-kubernetes#1734] opened 2022-06-08 08:29 UTC
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.2.2 on darwin_arm64
Kubernetes provider version: v2.11.0
Kubernetes version: 1.21 (EKS)
```

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "applicationset_argocd_applications" {
  manifest = {
    "apiVersion" = "argoproj.io/v1alpha1"
    "kind" = "ApplicationSet"
    "metadata" = {
      "name" = "foobar-applications"
      "namespace" = "argocd"
    }
    "spec" = {
      "generators" = [
        {
          "matrix" = {
            "generators" = [
              {
                "git" = {
                  "directories" = [
                    {
                      "path" = "microservices/*"
                    }
                  ]
                  "repoURL" = "git@bitbucket.org:example.org/foobar.git"
                  "revision" = "applicationset"
                }
              },
              {
                "list" = {
                  "elements" = [
                    {
                      "environment" = "staging"
                      "project" = "foobar-staging"
                    },
                  ]
                }
              },
            ]
          }
        },
      ]
      "template" = {
        "metadata" = {
          "name" = "{{path.basename}}-{{environment}}"
        }
        "spec" = {
          "destination" = {
            "name" = "{{cluster.name}}"
            "namespace" = "{{cluster.namespace}}"
          }
          "project" = "{{project}}"
          "source" = {
            "helm" = {
              "valueFiles" = [
                "values-{{environment}}.yaml",
              ]
            }
            "path" = "{{path}}"
            "repoURL" = "git@bitbucket.org:example.org/foobar.git"
            "targetRevision" = "applicationset"
          }
          "syncPolicy" = {
            "automated" = {
              "prune" = true
              "selfHeal" = true
            }
          }
        }
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/empeekdev/8ddd6bfee612d8b0391234dd12292108

### Steps to Reproduce

1. Copy tf code above 
2. Run `terraform apply`

### Expected Behavior
`ApplicationSet` resource created.

### Actual Behavior
Terraform throw an error.

### References

- GH-1351
-  GH-1603

**Comment by abhinavkhanna-sf** [comment] 2022-07-05 21:52
is there a workaround for this issue?

**Comment by alexsomesan** [comment] 2022-07-06 19:05
The fix for this just got released in version 2.12.1

**Closed by alexsomesan** 2022-07-06 19:05 UTC
Labels: bug, needs investigation

**Comment by abhinavkhanna-sf** [comment] 2022-07-06 21:22
@alexsomesan the fix did not work for me.

```
 hashicorp/kubernetes v2.12.1 
Terraform v1.2.3

```

I get an error because I updated the CRD version and couple of fields are removed  in the newer version but the Terraform state file still have them. in my case it is ksonnet.

```
AttributeName("spec"): [AttributeName("spec")] failed to morph object element
--
1335 | into object element: AttributeName("spec").AttributeName("generators"):
1336 | [AttributeName("spec").AttributeName("generators")] failed to morph object
1337 | element into object element:
1338 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0):
1339 | [AttributeName("spec").AttributeName("generators").ElementKeyInt(0)] failed
1340 | to morph tuple element into tuple element:
1341 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource"):
1342 | [AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource")]
1343 | failed to morph object element into object element:
1344 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template"):
1345 | [AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template")]
1346 | failed to morph object element into object element:
1347 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec"):
1348 | [AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec")]
1349 | failed to morph object element into object element:
1350 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec").AttributeName("source"):
1351 | [AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec").AttributeName("source")]
1352 | failed to morph object element into object element:
1353 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec").AttributeName("source").AttributeName("ksonnet"):
1354 | [AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec").AttributeName("source").AttributeName("ksonnet")]
1355 | failed to morph object element into object element:
1356 | AttributeName("spec").AttributeName("generators").ElementKeyInt(0).AttributeName("clusterDecisionResource").AttributeName("template").AttributeName("spec").AttributeName("source").AttributeName("ksonnet"):
1357 | type is nil
1358 |  
1359 | Error: Failed to morph manifest to OAPI type

```

workaround - delete all references to deprecated/removed fields in the state file.

**Comment by alexsomesan** [comment] 2022-07-06 22:06
@abhinavkhanna-sf Please share the exact configuration that breaks for you.

**Comment by alexsomesan** [comment] 2022-07-07 12:51
@abhinavkhanna-sf I am unable to reproduce your issue. I've used your sample resource together with the following variables and it works as expected:

```
locals {
  teams = toset(["foo", "bar"])
  envcode = "test"
}

variable "github_repo_name" {
  default = "test"
}

variable "github_owner" {
  default = "test"
}
```

It plans and applies correctly:
```
...
Plan: 2 to add, 0 to change, 0 to destroy.
kubernetes_manifest.applicationset_teams["bar"]: Creating...
kubernetes_manifest.applicationset_teams["foo"]: Creating...
kubernetes_manifest.applicationset_teams["bar"]: Creation complete after 1s
kubernetes_manifest.applicationset_teams["foo"]: Creation complete after 1s

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```
Can you share how your variables / locals get set?
