### ISSUE TITLE
`kubernetes_pod` failing to mount `kube-root-ca.crt` in kind and minikube cluster. Both single and multi node scenarios are affected

### ISSUE THREAD

**Issue by caniko** [hashicorp/terraform-provider-kubernetes#1696] opened 2022-04-20 12:48 UTC
### Terraform Version, Provider Version and Kubernetes Version

Terraform and kubernetes provider version:
```
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
```
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"2022-03-17T21:14:47Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected Resource(s)
- kubernetes_pod
- kubernetes_pod_v1
- kubernetes_service_account_v1
- kubernetes_role_v1
- kubernetes_role_binding_v1

### Terraform Configuration Files
hcl file:
```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/kubernetes" {
  version = "2.10.0"
  hashes = [
    ...
  ]
}
```

## [Multi-node Pod problem](https://github.com/kubernetes-sigs/kind/issues/2723#issue-1208269750): Kind
Link to [gist](https://gist.github.com/caniko/fc66fe7123d752c1cc9a7ce22a7f4e5a) containing both terraform file and debug output.

### Debug Output
`output_debug.txt` in [gist](https://gist.github.com/caniko/fc66fe7123d752c1cc9a7ce22a7f4e5a)

### Steps to Reproduce
1. In working dir place `main.tf` in [gist](https://gist.github.com/caniko/fc66fe7123d752c1cc9a7ce22a7f4e5a)
2. `terraform apply`
3. To get better stacktrace of error `kubectl -n fastapi describe pods`

### Expected Behavior
The `kubernetes_job_v1` should have been applied with no errors.

### Actual Behavior
Got errors.

## [Single node service account problem](https://github.com/kubernetes-sigs/kind/issues/2723#issuecomment-1103566051): Kind and minikube (kvm2)
Link to [gist](https://gist.github.com/caniko/b0cad5f0b428cf5b345d55f3c569626d) containing both terraform file and debug output. Note that I use `kubernetes_job_v1`, the job is applied without any problem. The issue is the Pod that raises the error, `kubectl describe pods`:
```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    22s                default-scheduler  Successfully assigned default/test-job-zlbtd to kind-worker
  Normal   Pulling      21s                kubelet            Pulling image "alpine"
  Normal   Pulled       18s                kubelet            Successfully pulled image "alpine" in 3.434231125s
  Normal   Created      18s                kubelet            Created container test-job-container
  Normal   Started      18s                kubelet            Started container test-job-container
  Warning  FailedMount  15s (x3 over 17s)  kubelet            MountVolume.SetUp failed for volume "kube-api-access-vprv2" : object "default"/"kube-root-ca.crt" not registered
```
### Debug Output
`output_debug.txt` in [gist](https://gist.github.com/caniko/b0cad5f0b428cf5b345d55f3c569626d)

### Steps to Reproduce
1. In working dir place `main.tf` in [gist](https://gist.github.com/caniko/b0cad5f0b428cf5b345d55f3c569626d)
2. `terraform apply`
3. To get better stacktrace of error `kubectl describe pods`

### Expected Behavior
The `kubernetes_job_v1` should have been applied with no errors.

### Actual Behavior
Got errors.

## Important Factoids and references
I am on bare-metal, and have tried with both [kind](https://github.com/kubernetes-sigs/kind/issues/2723) and [minikube](https://github.com/kubernetes/minikube/issues/13987).

## Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment] 2022-04-20 14:27
Hi @caniko,

The error message you can see in pod's events `MountVolume.SetUp failed for volume "kube-api-access-XXX" : object "default"/"kube-root-ca.crt" not registered` seems to be [this](https://github.com/kubernetes/kubernetes/issues/105204) Kubernetes issue that was introduced in `v1.22.2+`.

I have tried to reproduce this issue on my local kind cluster running on `v1.23.4` and I am getting the above pod error in both cases -- when I use your image and alpine. However, the job succeeds when I use alpine and fails when I use your image. It looks like you are getting the same result. I have tried both ways -- provider and YAML manifest. In both cases, I got the same result.

This doesn't seem to be the provider issue, but Kubernetes itself.

Thank you.

**Comment by caniko** [comment] 2022-04-20 15:43
Thank you! Hope that this is solved soon

**Comment by arybolovlev** [comment] 2022-04-21 07:26
Hi @caniko,

I will go ahead and close this issue, please follow the Kubernetes issue discussion. It seems that they have released a new version that contains the fix.

Thank you!

**Closed by arybolovlev** 2022-04-21 07:26 UTC
