### ISSUE TITLE
Terraform creates the incorrect plan with a volume

### ISSUE THREAD

**Issue by RomanKrasavtsev** [hashicorp/terraform-provider-kubernetes#1003] opened 2020-09-11 22:17 UTC
### Terraform Version and Provider Version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2

### Affected Resource(s)
- kubernetes_deployment

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "us-east-1"
  version = "3.2.0"
  profile = "aws-sandbox"
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "1.13.2"
}

data "aws_eks_cluster" "cluster" {
  name = "test"
}

data "aws_eks_cluster_auth" "cluster" {
  name = "test"
}

resource "kubernetes_deployment" "nginx" {
  metadata {
    name = "nginx"
    labels = {
      app = "nginx"
    }
    namespace = "default"
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "nginx"
      }
    }

    template {
      metadata {
        labels = {
          app = "nginx"
        }
      }

      spec {
        container {
          image = "nginx:1.19.2"
          name  = "nginx"
        }

        restart_policy = "Always"
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/RomanKrasavtsev/97b0236001c1b48809696b600a504ceb

### Expected Behavior
Terraform should create a plan without a volume

### Actual Behavior
Terraform shows the plan with a volume and 26 types

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

Amazon EKS 1.15 on AWS Fargate

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment] 2020-09-12 16:28
Hello Roman,

Thanks for raising this.

What you are seeing is actually expected behaviour, although a rather peculiar one. 
It is caused by the fact that the `volume` attribute is designated as "Computed" in Terraform schema. This is necessary to ensure that "built-in" volumes like the default service account secret do not show up as a change diff when not specified in Terraform configuration.

When an attribute is marked as computed in Terraform, you will see it showing up in the first plan as with a value of `(known after apply)`. This means the attribute will be not added by Terraform, but it will be set to any value the API might return for it.

As you may have noticed in the debug log you shared, the actual payload of the API call that created the deployment did not include any volumes. See here: https://gist.github.com/RomanKrasavtsev/97b0236001c1b48809696b600a504ceb#file-terraform-provider-kubernetes-issue-txt-L2304

Not just volumes do this, but also other attributes in you example as well. Have a look at `resources` (under `container`) or `strategy`. They behave the same way.
 
Computed is discussed in the Terraform documentation here: https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#computed

I hope this clears the matter up a bit.
I'll close the issue but feel free to re-open if you need more information.

**Closed by alexsomesan** 2020-09-12 16:28 UTC
Labels: bug
