### ISSUE TITLE
Aggregation rules in roles

### ISSUE THREAD

**Issue by NeQuissimus** [hashicorp/terraform-provider-kubernetes#888] opened 2020-06-17 16:24 UTC
### Description

New cluster roles can aggregate multiple cluster roles into one.
This is done by writing aggregation rules (see https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles).
This feature does not currently seem to be supported by this provider.

### Potential Terraform Configuration

```hcl
resource "kubernetes_cluster_role" "hypothetical_cluster_role" {
  metadata {
    name = "system:hypothetical"
  }

  aggregation_rule {
    cluster_role_selector {
      match_labels = {
        "rbac.example.com/aggregate-to-monitoring" = "true"
      }
    }
  }
}
```

Note that this means that `rules` will be auto-populated.
Currently, at least one `rule` block is required for a cluster role, this would need to change. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment] 2020-06-25 00:09
Hi, thanks for opening this issue. This seems to be a duplicate of https://github.com/hashicorp/terraform-provider-kubernetes/issues/356. I'll close this issue in favor of the old one, but feel free to add the :+1: reaction to the original issue, and that will help the community and maintainers prioritize it. Thanks

**Closed by dak1n1** 2020-06-25 00:09 UTC
Labels: enhancement

**Comment by NeQuissimus** [comment] 2020-06-25 13:26
Thank you! Sorry for creating a duplicate, weird that it did not come up in my search... :)
Added my :+1: there
