### ISSUE TITLE
unexpected new value error with Karpenter provisioner

### ISSUE THREAD

**Issue by hyungryuk** [hashicorp/terraform-provider-kubernetes#2162] opened 2023-06-26 06:33 UTC
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.5.0
Kubernetes provider version: v2.21.1
Kubernetes version: v1.27
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "kubernetes_manifest" "provisioner_sas" {
  manifest = {
    "apiVersion" = "karpenter.sh/v1alpha5"
    "kind"       = "Provisioner"
    "metadata"   = {
      "name" = "sample"
    }
    "spec" = {
      "limits" = {
        "resources" = {
          "cpu" = 1024
        }
      }
      "provider" = {
        "apiVersion"            = "extensions.karpenter.sh/v1alpha1"
        "kind"                  = "AWS"
        "securityGroupSelector" = {
          "karpenter.sh/discovery/$${cluster_name}-node" = "$${cluster_name}"
        }
        "subnetSelector" = {
          "karpenter.sh/discovery" = "$${cluster_name}"
        }
      }
      "requirements" = [
        {
          "key"      = "node.kubernetes.io/instance-type"
          "operator" = "In"
          "values"   = [
            "c5a.8xlarge",
          ]
        },
        {
          "key"      = "karpenter.sh/capacity-type"
          "operator" = "In"
          "values"   = [
            "on-demand",
          ]
        },
        {
          "key"      = "kubernetes.io/arch"
          "operator" = "In"
          "values"   = [
            "amd64",
          ]
        },
      ]
      "taints" = [
        {
          "effect" = "NoSchedule"
          "key"    = "workload"
          "value"  = "elasticsearch"
        },
      ]
      "ttlSecondsAfterEmpty"   = 300
      "ttlSecondsUntilExpired" = 172800
    }
  }
  depends_on = [argocd_application.karpenter]
}
```

### Panic Output

Error: Provider produced inconsistent result after apply
When applying changes to kubernetes_manifest.provisioner_sas, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.spec.requirements: new element 3 has appeared.
This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected Behavior
What should have happened?
run without error

### Actual Behavior
What actually happened?
resource created successfully in k8s. but terraform shows error

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment] 2023-06-30 17:27
Hi!

Can you try setting the `spec.requirements` field as computed, like this?
```
resource "kubernetes_manifest" "provisioner_sas" {
  manifest = {...
  }
  computed_fields = ["spec.requirements"]
```

Please let us know if that fixes the issue? More on computed fields, [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#computed-fields).

**Comment by hyungryuk** [comment] 2023-07-01 09:07
Hi. @alexsomesan  It works perfectly! 

Thanks for your help!

**Comment by alexsomesan** [comment] 2023-07-01 13:13
Awesome! Glad it worked out.
This is caused by the fact that the resource configuration specified a certain value for the "requirements" attribute (a list of three elements), but the API eventually returned a different value for it after apply (a list of four elements). By default, Terraform treats this as suspicious behavior because the value on the API does not match what the user requested. Setting the attribute as "computed" tells Terraform that this sort of behavior is expected for said attribute.

**Comment by hyungryuk** [comment] 2023-07-01 13:38
Great! What a detailed explanation!

thank you again :)

**Comment by jrhouston** [comment] 2023-07-05 02:48
Closing this as resolved 😄

**Closed by jrhouston** 2023-07-05 02:48 UTC
