### ISSUE TITLE
Service account creation errors out `Root resource was present, but now absent.`

### ISSUE THREAD

**Issue by unredundant** [hashicorp/terraform-provider-kubernetes#1844] opened 2022-09-25 14:27 UTC
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.0
Kubernetes provider version: 2.13.1
Kubernetes version: 1.24.0
```

### Affected Resource(s)

- kubernetes_service_account

### Terraform Configuration Files
```hcl
resource "kubernetes_service_account" "vault_auth" {
  metadata {
    name = "vault-auth"
  }
  secret {
    name = kubernetes_secret.vault-auth.metadata.0.name
  }

  lifecycle {
    ignore_changes = [
      image_pull_secret,
      secret
    ]
  }
}

resource "kubernetes_secret" "vault-auth" {
  metadata {
    name = "vault-auth"
    annotations = {
      "kubernetes.io/service-account.name" = "vault-auth"
    }
  }

  type = "kubernetes.io/service-account-token"
}

```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
Service account should be created as expected

### Actual Behavior
Provider errored out

### Important Factoids
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by andrea-defraia** [comment] 2022-09-26 12:01
I can confirm the same error using _v1 resources, rest of the code is same as above:
`module.csi.kubernetes_secret_v1.main: Creating...

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.csi.kubernetes_secret_v1.main, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: Root resource was present, but now absent.

│ This is a bug in the provider, which should be reported in the provider's own issue tracker`

**Comment by BBBmau** [comment] 2022-09-28 16:29
Thank you for bringing up this issue! We'll be closing this since this is a duplicate of #1830

**Closed by BBBmau** 2022-09-28 16:29 UTC
