### ISSUE TITLE
Import not supported for service account

### ISSUE THREAD

**Issue by captn3m0** [hashicorp/terraform-provider-kubernetes#268] opened 2019-01-07 06:05 UTC
### Terraform Version

`0.11.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_service_account

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output

```
Error: module.service-account.kubernetes_service_account.service-account (import id: monitoring/name): import module.name.service-account.kubernetes_service_account.service-account (id: monitoring/name): resource kubernetes_service_account doesn't support import
```

### Expected Behavior

The `service_account` resource should support imports and get imported.

### Actual Behavior
Received an error instead.

### Steps to Reproduce
1. Create a service account in kubernetes
2. Try to import it in terraform

**Comment by sosoriov** [comment] 2019-03-04 16:27
@alexsomesan if that's the case, how can I run my terraform plan if the SA already exist?

when I run the `apply` command I always get this:

```
Error: Error applying plan:

1 error(s) occurred:

* kubernetes_service_account.XXX: 1 error(s) occurred:

* kubernetes_service_account.XXX: serviceaccounts "XXX" already exists

```

thanks for your help

**Comment by wjam** [comment] 2019-03-25 18:30
@alexsomesan From my poking around the code & Kubernetes, it looks like it refers to the fact that the `kubernetes_secret` data resource also attempts to find the service account token that is created alongside service account and there is no obvious link in the API to say which service account token, if a service account has multiple, was the 'default' token for that service account.

I propose that a way to find default service account token would be to find all tokens associated with the service account and then either find the one created at the same time (or very close to?) as the service account or filter the tokens by those whose name has the service accounts name prefixed to it, as from my experience they all look like `[service-account-name]-token-[5chars]`.

**Comment by wjam** [comment] 2019-03-25 18:37
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L386 for those of interest

**Comment by pdecat** [comment] 2019-06-05 16:22
This was resolved by https://github.com/terraform-providers/terraform-provider-kubernetes/pull/377

**Comment by mstrejczek** [comment] 2019-10-22 08:22
Please have a look at https://github.com/terraform-providers/terraform-provider-kubernetes/pull/377#issuecomment-540126765 - importing service accounts does not work reliably 100% of time.

**Comment by therc** [comment] 2020-01-26 05:19
I see the same issue as @mstrejczek on EKS: sometimes the delta is 2s or so. Perhaps it should tolerate up to 5s to be safer? And if more than one secrets match within that time window, it could pick the oldest of them.

**Comment by alexsomesan** [comment] 2020-09-09 14:08
I tried reproducing this issue and I was able to successfully import a service account as described in the issue description.

Here's what I did:

```
» kubectl create sa test

serviceaccount/test created
----------------------------------------------------------------------------------------------------------------------------------

» kubectl get sa test -ojson

{
    "apiVersion": "v1",
    "kind": "ServiceAccount",
    "metadata": {
        "creationTimestamp": "2020-09-09T13:54:47Z",
        "name": "test",
        "namespace": "default",
        "resourceVersion": "225372",
        "selfLink": "/api/v1/namespaces/default/serviceaccounts/test",
        "uid": "3566da2d-ae9b-4591-ae96-83b0155cff6e"
    },
    "secrets": [
        {
            "name": "test-token-rn99t"
        }
    ]
}
----------------------------------------------------------------------------------------------------------------------------------

» cat main.tf

provider "kubernetes" {
    version = "~> 1.13"
}
resource "kubernetes_service_account" "test" {
  metadata {
    name = "test"
    namespace = "default"
  }
}
----------------------------------------------------------------------------------------------------------------------------------

» terraform init 

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/kubernetes versions matching "~> 1.13"...
- Using hashicorp/kubernetes v1.13.1 from the shared cache directory

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
----------------------------------------------------------------------------------------------------------------------------------

» terraform import kubernetes_service_account.test default/test

kubernetes_service_account.test: Importing from ID "default/test"...
kubernetes_service_account.test: Import prepared!
  Prepared kubernetes_service_account for import
kubernetes_service_account.test: Refreshing state... [id=default/test]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

----------------------------------------------------------------------------------------------------------------------------------

» terraform state list

kubernetes_service_account.test
----------------------------------------------------------------------------------------------------------------------------------

» terraform state show kubernetes_service_account.test

# kubernetes_service_account.test:
resource "kubernetes_service_account" "test" {
    automount_service_account_token = false
    default_secret_name             = "test-token-rn99t"
    id                              = "default/test"

    metadata {
        annotations      = {}
        generation       = 0
        labels           = {}
        name             = "test"
        namespace        = "default"
        resource_version = "225372"
        self_link        = "/api/v1/namespaces/default/serviceaccounts/test"
        uid              = "3566da2d-ae9b-4591-ae96-83b0155cff6e"
    }

    timeouts {}
}
----------------------------------------------------------------------------------------------------------------------------------

» terraform plan 

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

kubernetes_service_account.test: Refreshing state... [id=default/test]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
----------------------------------------------------------------------------------------------------------------------------------```

**Comment by alexsomesan** [comment] 2020-09-09 14:10
I'm closing this.
If you are still having this type of issue, especially if you are running into it while creating the cluster at the same time, please open a new issue and describe exactly the configuration and cluster details where you are encountering it.

**Closed by alexsomesan** 2020-09-09 14:10 UTC
Labels: bug, documentation
